-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.academic_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid,
  sourced_id text,
  provider text,
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['semester'::text, 'quarter'::text, 'year'::text, 'trimester'::text])),
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_current boolean NOT NULL DEFAULT false,
  metadata jsonb,
  data_classification text NOT NULL DEFAULT 'educational'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academic_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT academic_sessions_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.admin_audit_trail (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_user_id uuid NOT NULL,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'personal'::text,
  CONSTRAINT admin_audit_trail_pkey PRIMARY KEY (id),
  CONSTRAINT admin_audit_trail_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.api_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider text NOT NULL,
  model text,
  route text,
  status_code integer,
  latency_ms integer,
  prompt_tokens integer,
  completion_tokens integer,
  total_tokens integer,
  cost_cents numeric,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'anonymous'::text,
  CONSTRAINT api_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.assessment_analysis_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessment_id uuid,
  class_id uuid,
  teacher_id uuid,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'processing'::text,
  report_version integer NOT NULL DEFAULT 1,
  supersedes_report_id uuid,
  student_count integer,
  completion_rate numeric,
  avg_reasoning_score double precision,
  avg_evidence_score double precision,
  avg_response_length_words integer,
  data_quality jsonb,
  rubric_distributions jsonb,
  misconceptions jsonb,
  reasoning_patterns jsonb,
  evidence_patterns jsonb,
  engagement_indicators jsonb,
  question_effectiveness jsonb,
  suggested_actions jsonb,
  evidence_index jsonb,
  raw_ai_analysis text,
  processing_time_seconds numeric,
  ai_model_version text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  CONSTRAINT assessment_analysis_reports_pkey PRIMARY KEY (id),
  CONSTRAINT assessment_analysis_reports_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT assessment_analysis_reports_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT assessment_analysis_reports_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id),
  CONSTRAINT assessment_analysis_reports_supersedes_report_id_fkey FOREIGN KEY (supersedes_report_id) REFERENCES public.assessment_analysis_reports(id)
);
CREATE TABLE public.assessment_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessment_id uuid,
  asset_type text NOT NULL,
  asset_url text NOT NULL,
  generation_prompt text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  original_filename text,
  duration_seconds integer,
  max_duration_seconds integer,
  require_full_listen boolean NOT NULL DEFAULT true,
  CONSTRAINT assessment_assets_pkey PRIMARY KEY (id),
  CONSTRAINT assessment_assets_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id)
);
CREATE TABLE public.assessment_assignments (
  assessment_id uuid NOT NULL,
  student_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assessment_assignments_pkey PRIMARY KEY (assessment_id, student_id),
  CONSTRAINT assessment_assignments_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT assessment_assignments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.assessment_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid,
  assessment_id uuid,
  student_id uuid,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['ai_scored'::text, 'teacher_override'::text, 'teacher_comment'::text, 'review_requested'::text, 'review_resolved'::text, 'published'::text, 'audio_deleted'::text, 'submission_deleted'::text, 'score_changed'::text])),
  actor_id uuid,
  actor_role text NOT NULL CHECK (actor_role = ANY (ARRAY['ai'::text, 'teacher'::text, 'student'::text, 'admin'::text, 'system'::text])),
  previous_value jsonb,
  new_value jsonb,
  reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assessment_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT assessment_audit_log_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT assessment_audit_log_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT assessment_audit_log_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.assessment_integrity (
  assessment_id uuid NOT NULL,
  pause_threshold_seconds numeric,
  tab_switch_monitor boolean NOT NULL DEFAULT false,
  shuffle_questions boolean NOT NULL DEFAULT false,
  recording_limit_seconds integer NOT NULL DEFAULT 60,
  viewing_timer_seconds integer NOT NULL DEFAULT 20,
  pledge_enabled boolean NOT NULL DEFAULT false,
  pledge_version integer NOT NULL DEFAULT 1,
  pledge_text text,
  allow_grace_restart boolean NOT NULL DEFAULT false,
  data_classification text NOT NULL DEFAULT 'educational'::text,
  CONSTRAINT assessment_integrity_pkey PRIMARY KEY (assessment_id),
  CONSTRAINT assessment_integrity_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id)
);
CREATE TABLE public.assessment_question_standards (
  question_id uuid NOT NULL,
  standard_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assessment_question_standards_pkey PRIMARY KEY (question_id, standard_id),
  CONSTRAINT assessment_question_standards_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.assessment_questions(id),
  CONSTRAINT assessment_question_standards_standard_id_fkey FOREIGN KEY (standard_id) REFERENCES public.standards_nodes(id)
);
CREATE TABLE public.assessment_questions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  segment_id uuid,
  question_text text NOT NULL,
  question_type text,
  order_index integer NOT NULL,
  assessment_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  submission_id uuid,
  kind text NOT NULL DEFAULT 'initial'::text,
  parent_question_id uuid,
  evidence_upload text NOT NULL DEFAULT 'optional'::text CHECK (evidence_upload = ANY (ARRAY['disabled'::text, 'optional'::text, 'required'::text])),
  blooms_level text CHECK (blooms_level IS NULL OR (blooms_level = ANY (ARRAY['remember'::text, 'understand'::text, 'apply'::text, 'analyze'::text, 'evaluate'::text, 'create'::text]))),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  max_evidence_count smallint NOT NULL DEFAULT 1 CHECK (max_evidence_count >= 1 AND max_evidence_count <= 4),
  CONSTRAINT assessment_questions_pkey PRIMARY KEY (id),
  CONSTRAINT assessment_questions_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES public.assessment_segments(id),
  CONSTRAINT assessment_questions_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT assessment_questions_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT assessment_questions_parent_question_id_fkey FOREIGN KEY (parent_question_id) REFERENCES public.assessment_questions(id)
);
CREATE TABLE public.assessment_report_excerpts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessment_id uuid,
  submission_id uuid,
  question_id uuid,
  transcript_text text,
  start_ms integer,
  end_ms integer,
  asr_confidence numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'audio'::text,
  CONSTRAINT assessment_report_excerpts_pkey PRIMARY KEY (id),
  CONSTRAINT assessment_report_excerpts_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT assessment_report_excerpts_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT assessment_report_excerpts_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.assessment_questions(id)
);
CREATE TABLE public.assessment_restart_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessment_id uuid,
  student_id uuid,
  submission_id uuid,
  new_submission_id uuid,
  question_id uuid,
  restart_reason text NOT NULL,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assessment_restart_events_pkey PRIMARY KEY (id),
  CONSTRAINT assessment_restart_events_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT assessment_restart_events_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT assessment_restart_events_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT assessment_restart_events_new_submission_id_fkey FOREIGN KEY (new_submission_id) REFERENCES public.submissions(id),
  CONSTRAINT assessment_restart_events_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.assessment_questions(id)
);
CREATE TABLE public.assessment_segments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessment_id uuid,
  segment_type text NOT NULL,
  prompt text,
  time_limit_seconds integer,
  view_limit_seconds integer,
  order_index integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assessment_segments_pkey PRIMARY KEY (id),
  CONSTRAINT assessment_segments_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id)
);
CREATE TABLE public.assessment_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessment_id uuid,
  source_type text NOT NULL,
  source_reference text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  CONSTRAINT assessment_sources_pkey PRIMARY KEY (id),
  CONSTRAINT assessment_sources_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id)
);
CREATE TABLE public.assessment_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  subject text,
  grade_band text,
  blooms_level_avg text,
  description text,
  asset_url text,
  instructions text,
  target_language text,
  questions jsonb NOT NULL,
  rubrics jsonb NOT NULL,
  is_public boolean NOT NULL DEFAULT true,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT assessment_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.assessments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  class_id uuid,
  title text NOT NULL,
  subject text,
  target_language text,
  instructions text,
  status text NOT NULL DEFAULT 'draft'::text,
  authoring_mode text NOT NULL DEFAULT 'manual'::text,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  selected_asset_id uuid,
  socratic_enabled boolean NOT NULL DEFAULT false,
  socratic_follow_ups integer NOT NULL DEFAULT 1 CHECK (socratic_follow_ups >= 1 AND socratic_follow_ups <= 2),
  is_practice_mode boolean NOT NULL DEFAULT false,
  data_classification text NOT NULL DEFAULT 'educational'::text,
  has_class_report boolean NOT NULL DEFAULT false,
  latest_report_id uuid,
  scores_last_modified_at timestamp with time zone,
  assessment_profile text CHECK (assessment_profile IS NULL OR (assessment_profile = ANY (ARRAY['k6_formative'::text, '712_formative'::text, '712_summative'::text, 'higher_ed_viva'::text, 'language_proficiency'::text]))),
  profile_modified boolean NOT NULL DEFAULT false,
  profile_version integer NOT NULL DEFAULT 1,
  profile_override_keys ARRAY,
  hide_ai_score_from_students boolean DEFAULT false,
  require_teacher_review_before_release boolean DEFAULT false,
  disable_ai_feedback boolean DEFAULT false,
  uk_locale_config jsonb,
  oracy_strands ARRAY,
  context_type text DEFAULT 'lesson'::text,
  scaffold_level text DEFAULT 'heavy'::text,
  CONSTRAINT assessments_pkey PRIMARY KEY (id),
  CONSTRAINT assessments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT assessments_latest_report_id_fkey FOREIGN KEY (latest_report_id) REFERENCES public.assessment_analysis_reports(id)
);
CREATE TABLE public.class_enrollments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  class_id uuid NOT NULL,
  student_id uuid,
  teacher_id uuid,
  role text NOT NULL CHECK (role = ANY (ARRAY['student'::text, 'teacher'::text, 'ta'::text, 'observer'::text])),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'withdrawn'::text, 'completed'::text])),
  is_primary boolean NOT NULL DEFAULT true,
  sourced_id text,
  provider text,
  enrolled_at timestamp with time zone DEFAULT now(),
  withdrawn_at timestamp with time zone,
  data_classification text NOT NULL DEFAULT 'educational'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT class_enrollments_pkey PRIMARY KEY (id),
  CONSTRAINT class_enrollments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT class_enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT class_enrollments_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id)
);
CREATE TABLE public.classes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workspace_id uuid,
  name text NOT NULL,
  description text,
  access_mode text NOT NULL DEFAULT 'code'::text,
  created_at timestamp with time zone DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  sourced_id text,
  provider text,
  provider_metadata jsonb,
  school_id uuid,
  term_id uuid,
  CONSTRAINT classes_pkey PRIMARY KEY (id),
  CONSTRAINT classes_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT classes_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT classes_term_id_fkey FOREIGN KEY (term_id) REFERENCES public.academic_sessions(id)
);
CREATE TABLE public.clever_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  district_id uuid NOT NULL UNIQUE,
  clever_district_id text NOT NULL,
  access_token text,
  token_expires_at timestamp with time zone,
  scopes ARRAY,
  last_sync_at timestamp with time zone,
  sync_schedule text DEFAULT '0 2 * * *'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT clever_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT clever_credentials_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id)
);
CREATE TABLE public.credit_adjustments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  delta integer NOT NULL,
  reason text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'personal'::text,
  CONSTRAINT credit_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT credit_adjustments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT credit_adjustments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.cultural_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  year integer NOT NULL UNIQUE,
  headline text NOT NULL,
  price_snapshot text,
  top_song text,
  CONSTRAINT cultural_data_pkey PRIMARY KEY (id)
);
CREATE TABLE public.districts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  sourced_id text UNIQUE,
  provider text,
  metadata jsonb,
  retention_audio_days integer NOT NULL DEFAULT 30,
  retention_transcript_days integer NOT NULL DEFAULT 30,
  retention_log_days integer NOT NULL DEFAULT 90,
  is_active boolean NOT NULL DEFAULT true,
  timezone text DEFAULT 'America/New_York'::text,
  locale text DEFAULT 'en-US'::text,
  data_classification text NOT NULL DEFAULT 'anonymous'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT districts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.evidence_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  question_id uuid NOT NULL,
  submission_response_id uuid,
  original_filename text,
  storage_bucket text NOT NULL DEFAULT 'student-evidence'::text,
  storage_path text NOT NULL,
  file_size_bytes integer,
  mime_type text,
  width_px integer,
  height_px integer,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  analyzed_at timestamp with time zone,
  ai_description text,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  CONSTRAINT evidence_images_pkey PRIMARY KEY (id),
  CONSTRAINT evidence_images_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT evidence_images_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.assessment_questions(id),
  CONSTRAINT evidence_images_submission_response_id_fkey FOREIGN KEY (submission_response_id) REFERENCES public.submission_responses(id)
);
CREATE TABLE public.formative_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  teacher_id uuid NOT NULL,
  title text NOT NULL,
  prompt_template text,
  rubric_template text NOT NULL DEFAULT 'default'::text,
  due_at timestamp with time zone,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'live'::text, 'closed'::text])),
  type text NOT NULL DEFAULT 'pulse'::text CHECK (type = ANY (ARRAY['pulse'::text, 'studylab'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  learning_target text,
  max_turns integer DEFAULT 6,
  difficulty text DEFAULT 'standard'::text CHECK (difficulty = ANY (ARRAY['supportive'::text, 'standard'::text, 'challenge'::text])),
  artifact_required boolean DEFAULT true,
  show_score_to_student boolean NOT NULL DEFAULT true,
  show_summary_to_student boolean NOT NULL DEFAULT true,
  show_strengths_to_student boolean NOT NULL DEFAULT true,
  show_weaknesses_to_student boolean NOT NULL DEFAULT true,
  require_artifact boolean NOT NULL DEFAULT true,
  max_artifact_count smallint NOT NULL DEFAULT 1 CHECK (max_artifact_count >= 1 AND max_artifact_count <= 4),
  CONSTRAINT formative_activities_pkey PRIMARY KEY (id),
  CONSTRAINT formative_activities_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id)
);
CREATE TABLE public.formative_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  activity_id uuid NOT NULL,
  class_id uuid NOT NULL,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  teacher_id uuid,
  CONSTRAINT formative_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT formative_assignments_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.formative_activities(id),
  CONSTRAINT formative_assignments_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id),
  CONSTRAINT formative_assignments_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES auth.users(id)
);
CREATE TABLE public.formative_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  comment text NOT NULL,
  needs_resubmission boolean DEFAULT false,
  feedback_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT formative_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT formative_feedback_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.formative_submissions(id),
  CONSTRAINT formative_feedback_feedback_by_fkey FOREIGN KEY (feedback_by) REFERENCES auth.users(id)
);
CREATE TABLE public.formative_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL UNIQUE,
  rubric_scores jsonb NOT NULL DEFAULT '{}'::jsonb,
  feedback_audio_url text,
  feedback_text text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  accuracy integer,
  reasoning integer,
  clarity integer,
  transfer integer,
  overall integer,
  scored_by uuid,
  scored_at timestamp with time zone DEFAULT now(),
  CONSTRAINT formative_scores_pkey PRIMARY KEY (id),
  CONSTRAINT formative_scores_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.formative_submissions(id),
  CONSTRAINT formative_scores_scored_by_fkey FOREIGN KEY (scored_by) REFERENCES auth.users(id)
);
CREATE TABLE public.formative_submission_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  file_path text NOT NULL,
  file_type text NOT NULL CHECK (file_type = ANY (ARRAY['image'::text, 'audio'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT formative_submission_files_pkey PRIMARY KEY (id),
  CONSTRAINT formative_submission_files_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.formative_submissions(id)
);
CREATE TABLE public.formative_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  activity_id uuid NOT NULL,
  student_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'assigned'::text CHECK (status = ANY (ARRAY['assigned'::text, 'submitted'::text, 'reviewed'::text])),
  input_mode text CHECK (input_mode = ANY (ARRAY['scan'::text, 'voice_memo'::text, 'digital'::text, 'skeleton'::text, 'studylab'::text])),
  submitted_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  submission_data jsonb DEFAULT '{}'::jsonb,
  artifact_url text,
  audio_url text,
  reviewed_by uuid,
  CONSTRAINT formative_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT formative_submissions_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.formative_activities(id),
  CONSTRAINT formative_submissions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT formative_submissions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.integrity_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  question_id uuid,
  event_type text NOT NULL,
  duration_ms integer,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  CONSTRAINT integrity_events_pkey PRIMARY KEY (id),
  CONSTRAINT integrity_events_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT integrity_events_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.assessment_questions(id)
);
CREATE TABLE public.lti_launches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  platform_id uuid,
  user_id uuid,
  student_id uuid,
  teacher_id uuid,
  class_id uuid,
  message_type text NOT NULL,
  target_link_uri text,
  resource_link_id text,
  context_id text,
  roles ARRAY,
  jit_action text,
  raw_claims jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lti_launches_pkey PRIMARY KEY (id),
  CONSTRAINT lti_launches_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.lti_platforms(id),
  CONSTRAINT lti_launches_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT lti_launches_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT lti_launches_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id),
  CONSTRAINT lti_launches_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.lti_platforms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  issuer text NOT NULL,
  client_id text NOT NULL,
  deployment_id text NOT NULL,
  auth_endpoint text NOT NULL,
  token_endpoint text NOT NULL,
  jwks_uri text NOT NULL,
  supports_deep_linking boolean NOT NULL DEFAULT true,
  supports_grade_passback boolean NOT NULL DEFAULT true,
  district_id uuid,
  metadata jsonb,
  is_active boolean NOT NULL DEFAULT true,
  data_classification text NOT NULL DEFAULT 'educational'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lti_platforms_pkey PRIMARY KEY (id),
  CONSTRAINT lti_platforms_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id)
);
CREATE TABLE public.lti_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  state text NOT NULL UNIQUE,
  nonce text NOT NULL,
  platform_id uuid,
  target_link_uri text,
  login_hint text,
  lti_message_hint text,
  client_id text,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lti_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT lti_sessions_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.lti_platforms(id)
);
CREATE TABLE public.memories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  timeline_id uuid,
  author_name text NOT NULL,
  year integer NOT NULL,
  type text NOT NULL,
  content text NOT NULL,
  media_url text,
  location text,
  lat double precision,
  lng double precision,
  status text DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT memories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.oracy_progression (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  strand_type text NOT NULL,
  subskill text NOT NULL,
  baseline_value jsonb,
  latest_value jsonb,
  delta_notes text,
  self_reflection text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT oracy_progression_pkey PRIMARY KEY (id),
  CONSTRAINT oracy_progression_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.oracy_strand_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  assessment_id uuid,
  strand_type text NOT NULL CHECK (strand_type = ANY (ARRAY['physical'::text, 'linguistic'::text, 'cognitive'::text, 'social'::text])),
  subskill_markers jsonb NOT NULL DEFAULT '{}'::jsonb,
  baseline_comparison jsonb,
  exploratory_patterns jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT oracy_strand_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT oracy_strand_profiles_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT oracy_strand_profiles_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id)
);
CREATE TABLE public.platform_admins (
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'personal'::text,
  CONSTRAINT platform_admins_pkey PRIMARY KEY (user_id),
  CONSTRAINT platform_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.question_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid,
  question_id uuid,
  scorer_type text NOT NULL,
  score integer,
  justification text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  ai_analysis jsonb,
  CONSTRAINT question_scores_pkey PRIMARY KEY (id),
  CONSTRAINT question_scores_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT question_scores_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.assessment_questions(id)
);
CREATE TABLE public.report_claim_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid,
  claim_id text NOT NULL,
  rating text NOT NULL,
  note text,
  teacher_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  CONSTRAINT report_claim_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT report_claim_feedback_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.assessment_analysis_reports(id),
  CONSTRAINT report_claim_feedback_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id)
);
CREATE TABLE public.report_evidence_refs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid,
  claim_id text NOT NULL,
  excerpt_id uuid,
  submission_id uuid,
  question_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  CONSTRAINT report_evidence_refs_pkey PRIMARY KEY (id),
  CONSTRAINT report_evidence_refs_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.assessment_analysis_reports(id),
  CONSTRAINT report_evidence_refs_excerpt_id_fkey FOREIGN KEY (excerpt_id) REFERENCES public.assessment_report_excerpts(id),
  CONSTRAINT report_evidence_refs_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT report_evidence_refs_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.assessment_questions(id)
);
CREATE TABLE public.roster_sync_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  district_id uuid,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['clever'::text, 'oneroster'::text, 'canvas'::text, 'google'::text])),
  sync_type text NOT NULL DEFAULT 'full'::text CHECK (sync_type = ANY (ARRAY['full'::text, 'incremental'::text, 'delta'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  triggered_by uuid,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  stats jsonb DEFAULT '{}'::jsonb,
  error text,
  error_details jsonb,
  data_classification text NOT NULL DEFAULT 'educational'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT roster_sync_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT roster_sync_jobs_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id),
  CONSTRAINT roster_sync_jobs_triggered_by_fkey FOREIGN KEY (triggered_by) REFERENCES auth.users(id)
);
CREATE TABLE public.rubric_standards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rubric_id uuid,
  framework text NOT NULL,
  standard_code text,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  CONSTRAINT rubric_standards_pkey PRIMARY KEY (id),
  CONSTRAINT rubric_standards_rubric_id_fkey FOREIGN KEY (rubric_id) REFERENCES public.rubrics(id)
);
CREATE TABLE public.rubrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  segment_id uuid,
  rubric_type text NOT NULL,
  instructions text NOT NULL,
  scale_min integer NOT NULL DEFAULT 1,
  scale_max integer NOT NULL DEFAULT 5,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  assessment_id uuid,
  data_classification text NOT NULL DEFAULT 'educational'::text,
  CONSTRAINT rubrics_pkey PRIMARY KEY (id),
  CONSTRAINT rubrics_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES public.assessment_segments(id),
  CONSTRAINT rubrics_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id)
);
CREATE TABLE public.scaffold_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid,
  assessment_id uuid,
  scaffold_level text NOT NULL CHECK (scaffold_level = ANY (ARRAY['heavy'::text, 'light'::text, 'none'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scaffold_usage_pkey PRIMARY KEY (id),
  CONSTRAINT scaffold_usage_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT scaffold_usage_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id)
);
CREATE TABLE public.school_admins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  school_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'personal'::text,
  CONSTRAINT school_admins_pkey PRIMARY KEY (id),
  CONSTRAINT school_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT school_admins_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.school_descriptors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid UNIQUE,
  descriptors jsonb NOT NULL DEFAULT '["Exceptional", "Strong Standard", "Expected Standard", "Needs Attention", "Urgent Improvement"]'::jsonb,
  is_custom boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT school_descriptors_pkey PRIMARY KEY (id),
  CONSTRAINT school_descriptors_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.schools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  country text,
  school_type text,
  created_at timestamp with time zone DEFAULT now(),
  retention_audio_days integer NOT NULL DEFAULT 30,
  retention_transcript_days integer NOT NULL DEFAULT 30,
  retention_log_days integer NOT NULL DEFAULT 90,
  data_classification text NOT NULL DEFAULT 'anonymous'::text,
  district_id uuid,
  locale text NOT NULL DEFAULT 'US'::text CHECK (locale = ANY (ARRAY['US'::text, 'UK'::text])),
  locale_locked boolean NOT NULL DEFAULT false,
  CONSTRAINT schools_pkey PRIMARY KEY (id),
  CONSTRAINT schools_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.districts(id)
);
CREATE TABLE public.segment_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid,
  segment_id uuid,
  scorer_type text NOT NULL,
  score integer,
  justification text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT segment_scores_pkey PRIMARY KEY (id),
  CONSTRAINT segment_scores_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT segment_scores_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES public.assessment_segments(id)
);
CREATE TABLE public.session_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  duration_seconds integer NOT NULL DEFAULT 0,
  sessions_count integer NOT NULL DEFAULT 0,
  last_activity_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'educational'::text,
  CONSTRAINT session_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT session_tracking_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.standards_nodes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  set_id uuid NOT NULL,
  code text NOT NULL,
  title text,
  description text,
  node_type text NOT NULL DEFAULT 'standard'::text,
  parent_code text,
  sort_order integer,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT standards_nodes_pkey PRIMARY KEY (id),
  CONSTRAINT standards_nodes_set_id_fkey FOREIGN KEY (set_id) REFERENCES public.standards_sets(id)
);
CREATE TABLE public.standards_sets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  title text NOT NULL,
  subject text,
  jurisdiction text,
  organization text,
  version text,
  description text,
  source_url text,
  license text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT standards_sets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.student_review_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL UNIQUE,
  student_id uuid NOT NULL,
  student_note text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'reviewed'::text, 'updated'::text, 'no_change'::text])),
  teacher_response text,
  teacher_id uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT student_review_requests_pkey PRIMARY KEY (id),
  CONSTRAINT student_review_requests_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT student_review_requests_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT student_review_requests_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id)
);
CREATE TABLE public.students (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  class_id uuid,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text,
  student_code text UNIQUE,
  auth_user_id uuid,
  code_claimed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  disabled boolean NOT NULL DEFAULT false,
  consent_audio boolean NOT NULL DEFAULT false,
  consent_audio_at timestamp with time zone,
  consent_revoked_at timestamp with time zone,
  data_classification text NOT NULL DEFAULT 'educational'::text,
  sourced_id text,
  provider text,
  provider_metadata jsonb,
  last_provider_sync_at timestamp with time zone,
  eal_status boolean DEFAULT false,
  slcn_status boolean DEFAULT false,
  CONSTRAINT students_pkey PRIMARY KEY (id),
  CONSTRAINT students_class_id_fkey FOREIGN KEY (class_id) REFERENCES public.classes(id)
);
CREATE TABLE public.submission_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id uuid NOT NULL,
  question_id uuid NOT NULL,
  storage_bucket text NOT NULL DEFAULT 'student-recordings'::text,
  storage_path text NOT NULL,
  mime_type text,
  duration_seconds integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  transcript text,
  response_stage text NOT NULL DEFAULT 'primary'::text CHECK (response_stage = ANY (ARRAY['primary'::text, 'followup'::text])),
  ai_followup_question text,
  ai_followup_created_at timestamp with time zone,
  data_classification text NOT NULL DEFAULT 'audio'::text,
  processing_status text NOT NULL DEFAULT 'complete'::text CHECK (processing_status = ANY (ARRAY['pending'::text, 'transcribing'::text, 'generating'::text, 'complete'::text, 'error'::text])),
  processing_error text,
  processing_started_at timestamp with time zone,
  CONSTRAINT submission_responses_pkey PRIMARY KEY (id),
  CONSTRAINT submission_responses_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id),
  CONSTRAINT submission_responses_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.assessment_questions(id)
);
CREATE TABLE public.submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assessment_id uuid,
  student_id uuid,
  status text NOT NULL DEFAULT 'started'::text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  submitted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  scoring_status text NOT NULL DEFAULT 'pending'::text,
  scoring_started_at timestamp with time zone,
  scored_at timestamp with time zone,
  scoring_error text,
  integrity_pledge_accepted_at timestamp with time zone,
  integrity_pledge_ip_address text,
  integrity_pledge_version integer,
  review_status text NOT NULL DEFAULT 'pending'::text,
  teacher_comment text,
  published_at timestamp with time zone,
  final_score_override double precision,
  data_classification text NOT NULL DEFAULT 'educational'::text,
  override_reason text,
  override_reason_category text CHECK (override_reason_category IS NULL OR (override_reason_category = ANY (ARRAY['accent_dialect'::text, 'audio_quality'::text, 'accommodation'::text, 'off_task'::text, 'other'::text]))),
  override_timestamp timestamp with time zone,
  CONSTRAINT submissions_pkey PRIMARY KEY (id),
  CONSTRAINT submissions_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id),
  CONSTRAINT submissions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  category text,
  priority text,
  status text NOT NULL DEFAULT 'open'::text,
  requester_email text,
  related_user_id uuid,
  related_school_id uuid,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'personal'::text,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_related_user_id_fkey FOREIGN KEY (related_user_id) REFERENCES auth.users(id),
  CONSTRAINT support_tickets_related_school_id_fkey FOREIGN KEY (related_school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.system_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  provider text,
  severity text,
  message text NOT NULL,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'anonymous'::text,
  CONSTRAINT system_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.teacher_enabled_standards (
  teacher_id uuid NOT NULL,
  standards_set_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT teacher_enabled_standards_pkey PRIMARY KEY (teacher_id, standards_set_id),
  CONSTRAINT teacher_enabled_standards_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id),
  CONSTRAINT teacher_enabled_standards_standards_set_id_fkey FOREIGN KEY (standards_set_id) REFERENCES public.standards_sets(id)
);
CREATE TABLE public.teachers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  email text NOT NULL,
  first_name text,
  last_name text,
  country text,
  school_type text,
  teaching_level text,
  onboarding_stage text NOT NULL DEFAULT '0'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id uuid,
  workspace_id uuid,
  disabled boolean NOT NULL DEFAULT false,
  data_classification text NOT NULL DEFAULT 'personal'::text,
  standards_tagging_enabled boolean NOT NULL DEFAULT false,
  sourced_id text,
  provider text,
  provider_metadata jsonb,
  last_provider_sync_at timestamp with time zone,
  last_privacy_notice_shown timestamp with time zone,
  CONSTRAINT teachers_pkey PRIMARY KEY (id),
  CONSTRAINT teachers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.workspaces (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  school_id uuid,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  data_classification text NOT NULL DEFAULT 'anonymous'::text,
  locale text,
  CONSTRAINT workspaces_pkey PRIMARY KEY (id),
  CONSTRAINT workspaces_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);