/**
 * Trust Disclaimers
 * 
 * Per oracy_UK_build.md Section 11 and dev_team_final_alignment.md:
 * Mandatory disclaimers that must appear in sales decks, privacy docs, and onboarding.
 * 
 * SayVeritas UK is positioned as an "Oracy Evidence Platform" -
 * NOT a grading tool, judgement system, or inspection predictor.
 */

/**
 * Core trust disclaimers (non-negotiable)
 */
export const TRUST_DISCLAIMERS = {
    no_grading: {
        id: 'no_grading',
        short: 'Does not grade pupils',
        long: 'SayVeritas curates evidence and surfaces patterns. It does not assign grades to students.',
        icon: '🎓',
    },

    no_inspection_prediction: {
        id: 'no_inspection_prediction',
        short: 'Does not predict inspection outcomes',
        long: 'SayVeritas does not predict, estimate, or imply any inspection results. Inspection judgement remains solely with inspectors.',
        icon: '📋',
    },

    no_teacher_replacement: {
        id: 'no_teacher_replacement',
        short: 'Does not replace teacher judgement',
        long: 'Professional judgement about student progress, attainment, and needs remains entirely with qualified educators.',
        icon: '👩‍🏫',
    },

    no_safeguarding_automation: {
        id: 'no_safeguarding_automation',
        short: 'Does not automate safeguarding decisions',
        long: 'Safeguarding alerts are flagged for human review by the Designated Safeguarding Lead. AI does not make safeguarding decisions.',
        icon: '🛡️',
    },

    evidence_curation: {
        id: 'evidence_curation',
        short: 'SayVeritas curates evidence',
        long: 'SayVeritas curates evidence. Interpretation and judgement remain the responsibility of the school.',
        icon: '📊',
    },
} as const;

export type TrustDisclaimerId = keyof typeof TRUST_DISCLAIMERS;

/**
 * Context-specific disclaimers
 */
export const CONTEXT_DISCLAIMERS = {
    evidence_pack: 'This evidence pack is generated by SayVeritas to support school self-evaluation. All content is fully editable. Interpretation and professional judgement remain the responsibility of the school.',

    strand_profile: 'Strand markers indicate observed patterns in student responses. They do not represent grades, scores, or quality judgements.',

    progression_report: 'Progression data shows changes in observed markers over time. This data supports but does not replace teacher assessment of student learning.',

    cohort_analysis: 'Cohort patterns are provided for teacher insight. Individual student outcomes depend on many factors and should be assessed by qualified educators.',

    export_watermark: '© SayVeritas | Evidence for teacher judgement only | Not for inspection submission',
} as const;

/**
 * Get all disclaimers for a specific context
 */
export function getDisclaimersForContext(context: 'onboarding' | 'evidence_pack' | 'sales' | 'privacy'): string[] {
    const all = Object.values(TRUST_DISCLAIMERS);

    switch (context) {
        case 'onboarding':
            return all.map(d => d.short);

        case 'evidence_pack':
            return [
                CONTEXT_DISCLAIMERS.evidence_pack,
                TRUST_DISCLAIMERS.no_grading.long,
                TRUST_DISCLAIMERS.no_inspection_prediction.long,
            ];

        case 'sales':
            return all.map(d => `${d.icon} ${d.short}`);

        case 'privacy':
            return all.map(d => d.long);

        default:
            return all.map(d => d.short);
    }
}

/**
 * Disclaimer component props (for UI rendering)
 */
export interface DisclaimerProps {
    disclaimerId: TrustDisclaimerId;
    variant: 'short' | 'long' | 'with-icon';
}

/**
 * Get formatted disclaimer text
 */
export function getDisclaimerText(id: TrustDisclaimerId, variant: 'short' | 'long' | 'with-icon' = 'short'): string {
    const disclaimer = TRUST_DISCLAIMERS[id];

    switch (variant) {
        case 'long':
            return disclaimer.long;
        case 'with-icon':
            return `${disclaimer.icon} ${disclaimer.short}`;
        case 'short':
        default:
            return disclaimer.short;
    }
}

/**
 * Full trust statement for documentation
 */
export const FULL_TRUST_STATEMENT = `
## What SayVeritas UK Does Not Do

SayVeritas UK is an Oracy Evidence Platform. It is explicitly designed to support teachers and schools without overstepping into areas that require human professional judgement.

**SayVeritas does NOT:**
- ${TRUST_DISCLAIMERS.no_grading.long}
- ${TRUST_DISCLAIMERS.no_inspection_prediction.long}
- ${TRUST_DISCLAIMERS.no_teacher_replacement.long}
- ${TRUST_DISCLAIMERS.no_safeguarding_automation.long}

**SayVeritas DOES:**
- Curate evidence from student spoken responses
- Surface patterns across strands and subskills
- Track progression over time for teacher insight
- Generate editable evidence packs for school use
- Support teacher judgement with structured data

This positioning is non-negotiable and must be reflected consistently across all product surfaces, documentation, and communications.
`.trim();
